name: 'CA Image Text'
multiple: FALSE
category: 'Capital Azur'
enabled: TRUE
fields:
  image:
    type: image
    label: "Left side Image"
    options:
      '#required': TRUE
  title:
    type: text
    label: "Title"
    options:
      '#default_value': 'LES FINTECHS AU SERVICE DE LA CROISSANCE EN AFRIQUE'
  description:
    type: textarea
    label: "Description"
    options:
      '#default_value': "La raison d'être de Capital Azur : Favoriser l'inclusion financière en Afrique afin d'accompagner le continent dans sa croissance.\nC'est pour cela que nous nous reposons sur le State Of The Art de la technologie. Fintechs, Blockchain, Mobile Banking, Digital Banking.. sont autant de moyens que nous mettons en oeuvre pour répondre à vos besoins, qui que vous soyez, où que vous voyez.."
  button_label:
    type: text
    label: "Button Label"
    options:
      '#default_value': 'EN SAVOIR PLUS'
  button_url:
    type: text
    label: "Button URL"
    options:
      '#default_value': '#'
