name: 'CA Services'
multiple: TRUE
category: 'Capital Azur'
enabled: TRUE
limit: 10
fields:
  icon:
    type: image
    label: "Service Icon (SVG or PNG)"
    options:
      '#required': TRUE
  label:
    type: text
    label: "Service Label"
    options:
      '#required': TRUE
  link_url:
    type: text
    label: "Link URL (optional)"
    options:
      '#required': FALSE
extra_fields:
  weight: 999
  group_header:
    g_title: 'Section Header'
    section_title:
      type: text
      label: 'Section Title'
      options:
        '#default_value': 'DES SERVICES INNOVANTS POUR UN QUOTIDIEN SIMPLIFIÉ.'
    section_description:
      type: textarea
      label: 'Section Description'
      options:
        '#default_value': "Capital Azur accompagne l'ensemble de sa clientèle dans leurs projets à toutes les étapes de leurs vie."
  group_config:
    g_title: 'Carousel Configuration'
    arrows:
      type: checkbox
      label: 'Show arrows'
      options:
        '#checked': TRUE
    autoLoop:
      type: checkbox
      label: 'Auto slide'
      options:
        '#checked': FALSE
    loopSpeed:
      type: number
      label: 'Auto slide speed (ms)'
      options:
        '#default_value': 4000
    visible_items:
      type: number
      label: 'Visible items on desktop'
      options:
        '#default_value': 4
