# settings.yml in Drupal
fields:
 collection:
 type: json_api_collection
 options:
 '#resource': 'node--vactory_news'
 '#filters':
 fields:
 node--vactory_news: 'title,field_vactory_date,field_vactory_excerpt'
 include: 'field_vactory_media'
 '#pagination':
 limit: 10
 '#sort': '-created'