name: 'CA Intro'
multiple: FALSE
category: 'Capital Azur'
enabled: TRUE
fields:
  title:
    type: text
    label: "Title"
    options:
      '#default_value': 'VOTRE SATISFACTION, NOTRE PASSION'
  description:
    type: textarea
    label: "Description"
    options:
      '#default_value': "Découvrez Capital Azur, la première banque 100% Digitale en Afrique et oubliez la paperasse et les frais cachés.\nAvec tous nos outils dédiés aux besoins de tous nos clients (Particuliers, Entreprises, Corporate), Nous vous accompagnons chaque jour pour réaliser vos projets de vie."
  button_label:
    type: text
    label: "Button Label"
    options:
      '#default_value': 'A PROPOS DE NOUS'
  button_url:
    type: text
    label: "Button URL"
    options:
      '#default_value': '#'
