name: 'CA Footer'
multiple: FALSE
category: 'Capital Azur'
enabled: TRUE
fields:
  social_linkedin_url:
    type: text
    label: "LinkedIn URL"
    options:
      '#default_value': '#'
  social_youtube_url:
    type: text
    label: "YouTube URL"
    options:
      '#default_value': '#'
  social_twitter_url:
    type: text
    label: "Twitter URL"
    options:
      '#default_value': '#'
  nav_1_label:
    type: text
    label: "Nav 1 label"
    options:
      '#default_value': 'NOUS CONTACTER'
  nav_1_url:
    type: text
    label: "Nav 1 URL"
    options:
      '#default_value': '#'
  nav_2_label:
    type: text
    label: "Nav 2 label"
    options:
      '#default_value': 'MENTIONS LEGALES'
  nav_2_url:
    type: text
    label: "Nav 2 URL"
    options:
      '#default_value': '#'
  nav_3_label:
    type: text
    label: "Nav 3 label"
    options:
      '#default_value': 'PLAN DU SITE'
  nav_3_url:
    type: text
    label: "Nav 3 URL"
    options:
      '#default_value': '#'
  copyright_text:
    type: text
    label: "Copyright text"
    options:
      '#default_value': '@2019 CAPITAL AZUR'
  dev_text:
    type: text
    label: "Development text"
    options:
      '#default_value': 'Conception et developpement'
  dev_url:
    type: text
    label: "Development URL"
    options:
      '#default_value': '#'
  dev_badge_text:
    type: text
    label: "Development badge text"
    options:
      '#default_value': 'VOID'
