<?php

namespace Drupal\appointment\Controller;

use Drupal\Core\Controller\ControllerBase;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\Core\File\FileSystemInterface;
use Drupal\Core\TempStore\PrivateTempStoreFactory;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;

/**
 * Serves CSV exports generated by batch.
 */
class AdminExportDownloadController extends ControllerBase {

  public function __construct(
    protected FileSystemInterface $fileSystem,
    protected PrivateTempStoreFactory $tempStoreFactory,
  ) {}

  public static function create(ContainerInterface $container): self {
    return new self(
      $container->get('file_system'),
      $container->get('tempstore.private'),
    );
  }

  public function download(string $token): BinaryFileResponse {
    $store = $this->tempStoreFactory->get('appointment_admin_export');
    $data = (array) ($store->get($token) ?? []);

    if (empty($data['uri']) || ($data['status'] ?? '') !== 'ready') {
      throw new \Symfony\Component\HttpKernel\Exception\NotFoundHttpException();
    }

    $path = $this->fileSystem->realpath((string) $data['uri']);
    if (!$path || !is_file($path)) {
      throw new \Symfony\Component\HttpKernel\Exception\NotFoundHttpException();
    }

    $filename = basename($path);
    $response = new BinaryFileResponse($path);
    $response->setContentDisposition(ResponseHeaderBag::DISPOSITION_ATTACHMENT, $filename);

    // One-time download.
    $store->delete($token);

    return $response;
  }

}

